### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by bsakweson** [google/gousb#47] opened 2018-09-04 16:29 UTC
UBS plugged and unplugged events:

I am unable to locate plugged and unplugged events in this package. It would be nice to know if a usb device is plugged or unplugged so that implementors can better manage reconnection when an unplugged device is later plugged-in.

I looked through the code but could hardly find anything close to that, is it there and I am just missing it? If not, is this something that could be implemented?

**Comment by zagrodzki** [comment] 2018-09-04 16:39
The package doesn't support hotplug at all at this point. There is some work done towards supporting hotplug in https://github.com/google/gousb/pull/32, but it's unfinished and didn't see any updates for a long time now. It's something that could be implemented if you'd like to work on it.

**Comment by Elemecca** [comment] 2018-10-20 21:03
This issue is a duplicate of #8 and should be closed as such.

**Closed** 2018-11-05 07:59 UTC
