### ISSUE TITLE
restore Timeout as a field on InEndpoint

### ISSUE THREAD

**Issue by notnot** [google/gousb#56] opened 2018-10-26 21:43 UTC
In the Async API issue i read about accidentally hiding the InEndpoint Timeout and the suggestion to expose it again. Please do! I don't know how to exit cleanly when a goroutine is blocked on a Read().

**Comment by zagrodzki** [comment] 2018-11-05 07:58
Duplicate of #25

**Closed by zagrodzki** 2018-11-05 07:58 UTC
